### ISSUE TITLE
Inventory Crafter Mod/ Decorative Block Support Blocks

### ISSUE THREAD

**Issue by f0kx** [SiverDX/whimscape-unofficial-additions#1]
[InventoryCrafting.zip](https://github.com/SiverDX/whimscape-unofficial-additions/files/12197842/InventoryCrafting.zip)
[DecorativeBlock.zip](https://github.com/SiverDX/whimscape-unofficial-additions/files/12197844/DecorativeBlock.zip)

**Comment by f0kx** [comment]
you can take a look and if you like it you can add it

**Comment by f0kx** [comment]
![image](https://github.com/SiverDX/whimscape-unofficial-additions/assets/14795020/2088ab49-113f-40f6-aa76-2cefe8d5e08c)
![image](https://github.com/SiverDX/whimscape-unofficial-additions/assets/14795020/d9dd8dd3-06e0-49c4-ad21-109813e43449)

**Comment by f0kx** [comment]
![image](https://github.com/SiverDX/whimscape-unofficial-additions/assets/14795020/33aa1f27-489c-4f9c-8a68-68f4866a360d)

**Comment by SiverDX** [comment]
Added them in, many thanks 👍

**Comment by f0kx** [comment]
When i add more textures can i upload it here?

**Comment by SiverDX** [comment]
yeah either here, or you can fork the repository and make a pull request

**Comment by f0kx** [comment]
[WhimUA.zip](https://github.com/SiverDX/whimscape-unofficial-additions/files/12208282/WhimUA.zip)
![Screenshot 2023-07-30 021544](https://github.com/SiverDX/whimscape-unofficial-additions/assets/14795020/0216722b-8de9-41a5-958d-783c07a3dc60)
![Screenshot 2023-07-30 021450](https://github.com/SiverDX/whimscape-unofficial-additions/assets/14795020/75bd96fd-6ba5-4239-a043-511d6eaa1644)
![Screenshot 2023-07-30 021306](https://github.com/SiverDX/whimscape-unofficial-additions/assets/14795020/ff22bf81-7cd2-43a1-9472-415442316db1)

**Comment by f0kx** [comment]
Add Textures
GUI - FramedBlocks Mod
Posts & Bundles - Valhelsia Structures Mod 
Palisades - decorativeBlocks Mod

**Comment by f0kx** [comment]
Zip is above Pictures

**Comment by f0kx** [comment]
![image](https://github.com/SiverDX/whimscape-unofficial-additions/assets/14795020/7754c14d-5aa0-4871-8a88-37ebc26bea98)
working on gui od sophisticated backpacks RN

**Comment by f0kx** [comment]
![image](https://github.com/SiverDX/whimscape-unofficial-additions/assets/14795020/abdf6dc7-36c0-4d09-9216-c8016a8aec8a)
HUD is ready and some essential icons

**Comment by f0kx** [comment]
[assets.zip](https://github.com/SiverDX/whimscape-unofficial-additions/files/12209446/assets.zip)

**Comment by SiverDX** [comment]
Added them with some tweaks
